### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stonexer** [stonexer/yab-fetch#2]
## yab-fetch

- [x] CI
- [x] Discuss middleware
- [x] Basic fetch, createFetch
- [x] Middlewares and default behaviour
- [x] Test
- [ ] Improve type definition
- [ ] example middleware @xianchenxc
